config.load_autoconfig(False)
# import pathlib
# pathlib.Path("/home/chad/.cache/colors.py").parent.resolve()
config.source('/home/chad/.cache/wal/colors.py')
c.colors.completion.category.bg = "#171b20"
c.colors.completion.category.border.bottom = "#3b4b58"
c.colors.completion.category.border.top = "#29343d"
c.colors.completion.category.fg = "#3b4b58"
c.colors.completion.even.bg = "#171b20"
c.colors.completion.item.selected.bg = "#29343d"
c.colors.completion.item.selected.border.bottom = "#29343d"
c.colors.completion.item.selected.border.top = "#29343d"
c.colors.completion.item.selected.fg = "#dee1e6"
c.colors.completion.match.fg = "#dee1e6"
c.colors.completion.odd.bg = "#171b20"
c.colors.completion.scrollbar.bg = "#171b20"
c.colors.completion.scrollbar.fg = "#9ce5c0"
c.colors.downloads.bar.bg = "#29343d"
c.colors.downloads.error.bg = "#f9929b"
c.colors.downloads.error.fg = "#dee1e6"
c.colors.downloads.start.bg = "#7ed491"
c.colors.downloads.start.fg = "#dee1e6"
c.colors.downloads.stop.bg = "#171b20"
c.colors.downloads.stop.fg = "#dee1e6"
c.colors.downloads.system.bg = "none"
c.colors.downloads.system.fg = "none"
c.colors.hints.fg = "#29343d"
c.colors.hints.match.fg = "#7ed491"
c.colors.messages.error.bg = "#f9929b"
c.colors.messages.error.border = "#f9929b"
c.colors.messages.error.fg = "#dee1e6"
c.colors.messages.info.bg = "#29343d"
c.colors.messages.info.border = "#29343d"
c.colors.messages.info.fg = "#dee1e6"
c.colors.messages.warning.bg = "#f9929b"
c.colors.messages.warning.border = "#f9929b"
c.colors.messages.warning.fg = "#dee1e6"
c.colors.prompts.bg = "#171b20"
c.colors.prompts.border = "1px solid gray"
c.colors.prompts.fg = "#dee1e6"
c.colors.prompts.selected.bg = "#171b20"
c.colors.statusbar.caret.bg = "#ccaced"
c.colors.statusbar.caret.fg = "#dee1e6"
c.colors.statusbar.caret.selection.bg = "#ccaced"
c.colors.statusbar.caret.selection.fg = "#dee1e6"
c.colors.statusbar.command.bg = "#21262e"
c.colors.statusbar.command.fg = "#dee1e6"
c.colors.statusbar.command.private.bg = "#29343d"
c.colors.statusbar.command.private.fg = "#dee1e6"
c.colors.statusbar.insert.bg = "#7ed491"
c.colors.statusbar.insert.fg = "#dee1e6"
c.colors.statusbar.normal.bg = "#29343d"
c.colors.statusbar.normal.fg = "#b6beca"
c.colors.statusbar.passthrough.bg = "#a3b8ef"
c.colors.statusbar.passthrough.fg = "#b6beca"
c.colors.statusbar.private.bg = "#21262e"
c.colors.statusbar.private.fg = "#b6beca"
c.colors.statusbar.progress.bg = "#dee1e6"
c.colors.statusbar.url.fg = "#b6beca"
c.colors.statusbar.url.hover.fg = "#9ce5c0"
c.colors.statusbar.url.success.https.fg = "#eaeaea"
c.colors.statusbar.url.warn.fg = "#fbdf90"
c.colors.tabs.bar.bg = "#13171b"
c.colors.tabs.even.bg = "#13171b"
c.colors.tabs.even.fg = "#dee1e6"
c.colors.tabs.indicator.error = "#f9929b"
c.colors.tabs.odd.bg = "#13171b"
c.colors.tabs.odd.fg = "#dee1e6"
# c.colors.tabs.selected.even.bg = "#171b20"
# c.colors.tabs.selected.even.fg = "#a3b8ef"
# c.colors.tabs.selected.odd.bg = "#171b20"
# c.colors.tabs.selected.odd.fg = "#a3b8ef"
c.statusbar.padding['bottom'] = 10
c.statusbar.padding['left'] = 10
c.statusbar.padding['right'] = 10
c.statusbar.padding['top'] = 10
c.statusbar.show = "in-mode"
c.tabs.indicator.width = 0
c.tabs.max_width = -1
c.tabs.padding['bottom'] = 6
c.tabs.padding['left'] = 15
c.tabs.padding['right'] = 15
c.tabs.padding['top'] = 6
c.tabs.position = "top"
c.tabs.show = "always"
c.tabs.title.alignment = "center"
c.downloads.location.directory = '~/Downloads'
# c.editor.command = ['st', '-e', 'nvim', '{file}'].tabs.title.format = "{current_title}"
c.editor.command = ['st',  'nvim',  '-f', '{file}']
config.bind('<Ctrl-E>', 'open-editor', mode='insert')
config.bind(',p', 'spawn --userscript qute-pass --dmenu-invocation "rofi -d" --username-target secret --username-pattern "[Uu]sername: (.+)"')
config.bind(',P', 'spawn --userscript qute-pass --dmenu-invocation "rofi -d" --username-target secret --username-pattern "[Uu]sername: (.+)" --password-only')
# c.url.default_page = "https://gs.is-a.dev/startpage/"
# c.url.start_pages = "https://gs.is-a.dev/startpage/"
c.url.default_page = "file:///home/chad/.config/firefox/rice/index.html"
c.url.start_pages = "file:///home/chad/.config/firefox/rice/index.html"
