--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/chad/Pictures/cavern-BB263.png_16x9.jpg"

-- Special
background="#00021C"
foreground="#96a3e8"
cursor="#96a3e8"

-- Colors
color0="#00021C"
color1="#0E2399"
color2="#142BAC"
color3="#2339B6"
color4="#1D36C1"
color5="#233CC6"
color6="#3049D3"
color7="#96a3e8"
color8="#6972a2"
color9="#0E2399"
color10="#142BAC"
color11="#2339B6"
color12="#1D36C1"
color13="#233CC6"
color14="#3049D3"
color15="#96a3e8"
